In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [7]:
df = pd.read_csv("airline_dataset.csv")

In [9]:
df.head()
df.shape

(1048575, 18)

In [11]:
df.columns.tolist()
df.info()
df.isnull().sum()
df.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1048575 entries, 0 to 1048574
Data columns (total 18 columns):
 #   Column               Non-Null Count    Dtype
---  ------               --------------    -----
 0   year                 1048575 non-null  int64
 1   month                1048575 non-null  int64
 2   day_of_month         1048575 non-null  int64
 3   day_of_week          1048575 non-null  int64
 4   fl_date              1048575 non-null  object
 5   origin               1048575 non-null  object
 6   origin_city_name     1048575 non-null  object
 7   origin_state_nm      1048575 non-null  object
 8   dep_time             1026022 non-null  float64
 9   taxi_out             1025450 non-null  float64
 10  wheels_off           1025450 non-null  float64
 11  wheels_on            1024898 non-null  float64
 12  taxi_in              1024898 non-null  float64
 13  cancelled            1048575 non-null  int64
 14  air_time             1022824 non-null  float64
 15  distance             1048575 non-null  int64
 16  weather_delay        1048575 non-null  int64
 17  late_aircraft_delay  1048575 non-null  int64
dtypes: float64(6), int64(8), object(4)
memory usage: 144.0+ MB

,year,month,day_of_month,day_of_week,dep_time,taxi_out,wheels_off,wheels_on,taxi_in,cancelled,air_time,distance,weather_delay,late_aircraft_delay
count,1048575.0,1.048575e+06,1.048575e+06,1.048575e+06,1.026022e+06,1.025450e+06,1.025450e+06,1.024898e+06,1.024898e+06,1.048575e+06,1.022824e+06,1.048575e+06,1.048575e+06,1.048575e+06
mean,2024.0,1.478081e+00,1.530512e+01,3.893483e+00,1.325074e+03,1.825012e+01,1.349996e+03,1.476156e+03,8.082517e+00,2.222635e-02,1.162270e+02,8.345389e+02,1.194321e+00,5.326660e+00
std,0.0,4.995196e-01,8.585503e+00,2.010038e+00,4.972990e+02,1.044025e+01,4.980426e+02,5.198682e+02,6.512591e+00,1.474190e-01,7.091204e+01,5.923104e+02,2.005819e+01,2.975676e+01
min,2024.0,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,0.000000e+00,8.000000e+00,3.100000e+01,0.000000e+00,0.000000e+00
25%,2024.0,1.000000e+00,8.000000e+00,2.000000e+00,9.110000e+02,1.200000e+01,9.290000e+02,1.058000e+03,4.000000e+00,0.000000e+00,6.400000e+01,4.020000e+02,0.000000e+00,0.000000e+00
50%,2024.0,1.000000e+00,1.500000e+01,4.000000e+00,1.323000e+03,1.500000e+01,1.337000e+03,1.510000e+03,6.000000e+00,0.000000e+00,1.000000e+02,6.920000e+02,0.000000e+00,0.000000e+00
75%,2024.0,2.000000e+00,2.300000e+01,6.000000e+00,1.736000e+03,2.100000e+01,1.750000e+03,1.914000e+03,9.000000e+00,0.000000e+00,1.470000e+02,1.069000e+03,0.000000e+00,0.000000e+00
max,2024.0,2.000000e+00,3.100000e+01,7.000000e+00,2.400000e+03,2.130000e+02,2.400000e+03,2.400000e+03,4.440000e+02,1.000000e+00,7.230000e+02,5.095000e+03,1.804000e+03,2.100000e+03

In [13]:
df["Flight_Status"] = df["cancelled"].map({
    0: "Operated",
    1: "Cancelled"
})

In [15]:
df["Flight_Status"].value_counts()

Flight_Status
Operated     1025269
Cancelled      23306
Name: count, dtype: int64

In [17]:
df["Month_Name"] = pd.to_datetime(
    df["month"],
    format="%m"
).dt.month_name()

In [19]:
df["Month_Name"].head()

0    January
1    January
2    January
3    January
4    January
Name: Month_Name, dtype: object

In [21]:
df["Weather_Delay_Category"] = pd.cut(
    df["weather_delay"],
    bins=[-1, 0, 30, 60, 1000],
    labels=[
        "No Delay",
        "Low Delay",
        "Medium Delay",
        "High Delay"
    ]
)

In [23]:
df["Weather_Delay_Category"].value_counts()

Weather_Delay_Category
No Delay        1032680
Low Delay          7859
High Delay         5130
Medium Delay       2835
Name: count, dtype: int64

In [25]:
print("Total Flights:", len(df))

print("Cancelled Flights:",
      df["cancelled"].sum())

print("Average Distance:",
      round(df["distance"].mean(), 2))

print("Average Air Time:",
      round(df["air_time"].mean(), 2))

Total Flights: 1048575
Cancelled Flights: 23306
Average Distance: 834.54
Average Air Time: 116.23

In [27]:
df[[
    "air_time",
    "distance",
    "weather_delay",
    "late_aircraft_delay"
]].isnull().sum()

air_time               25751
distance                   0
weather_delay              0
late_aircraft_delay        0
dtype: int64

In [29]:
df["weather_delay"] = df["weather_delay"].fillna(0)

df["late_aircraft_delay"] = df["late_aircraft_delay"].fillna(0)

df["air_time"] = df["air_time"].fillna(
    df["air_time"].median()
)

In [31]:
df["Delay_Impact"] = (
    df["weather_delay"] +
    df["late_aircraft_delay"]
)

In [33]:
df["Delay_Severity"] = pd.cut(
    df["Delay_Impact"],
    bins=[-1,0,30,60,10000],
    labels=[
        "No Delay",
        "Low",
        "Medium",
        "High"
    ]
)

In [35]:
df["Delay_Severity"].value_counts()

Delay_Severity
No Delay    939401
Low          50303
High         33254
Medium       25617
Name: count, dtype: int64

In [37]:
df["origin"].value_counts().head(10)

origin
ATL    50297
DFW    45521
DEN    44327
ORD    39179
CLT    31667
PHX    29683
LAX    28874
LAS    28492
MCO    27392
LGA    24990
Name: count, dtype: int64

In [39]:
monthly_flights = (
    df.groupby("Month_Name")
    .size()
    .reset_index(name="Flights")
)

monthly_flights

  Month_Name  Flights
0   February   501304
1    January   547271

In [41]:
print("Total Flights:", len(df))

print("Cancelled Flights:",
      df["cancelled"].sum())

print("Cancellation Rate:",
      round(df["cancelled"].mean()*100,2),
      "%")

print("Average Air Time:",
      round(df["air_time"].mean(),2))

print("Average Distance:",
      round(df["distance"].mean(),2))

Total Flights: 1048575
Cancelled Flights: 23306
Cancellation Rate: 2.22 %
Average Air Time: 115.83
Average Distance: 834.54

In [43]:
sample_df = df.sample(
    n=100000,
    random_state=42
)

sample_df.to_csv(
    "airlineops_tableau.csv",
    index=False
)

print("Tableau Dataset Created Successfully")

Tableau Dataset Created Successfully

In [45]:
df.to_csv(
    "airlineops_cleaned.csv",
    index=False
)